
import re
import tkinter

#Entry vars
EXPORTSELECTION = 'exportselection'
FG = 'fg'
FONT = 'font'
FOREGROUND = 'foreground'
HIGHLIGHTBACKGROUND = 'highlightbackground'
INSERTBORDERWIDTH = 'insertborderwidth'
INSERTOFFTIME = 'insertofftime'
INSERTONTIME = 'insertontime'
INSERTWIDTH = 'insertwidth'
SELECTBORDERWIDTH = 'selectborderwidth'
SELECTFOREGROUND = 'selectforeground'
SHOW = 'show'
STATE = 'state'
TAKEFOCUS = 'takefocus'
TEXTVARIABLE = 'textvariable'
VALIDATE = 'validate'
VALIDATECOMMAND = 'validatecommand'
VCMD = 'vcmd'
WIDTH = 'width'
XSCROLLCOMMAND = 'xscrollcommand'

#Pack and grid vars
AFTER = 'after'
ANCHOR = 'anchor'
BEFORE = 'before'
EXPAND = 'expand'
FILL = 'fill'
IN_ = 'in_'
IPADX = 'ipadx'
IPADY = 'ipady'
PADX = 'padx'
PADY = 'pady'
SIDE = 'side'
COLUMN = 'column'
COLUMNSPAN = 'columnspan'
ROW = 'row'
ROWSPAN = 'rowspan'
STICKY = 'sticky'
