
# Entry arguments
from typing import Literal


EXPORTSELECTION: Literal['exportselection'] = 'exportselection'
FG: Literal['fg'] = 'fg'
FONT: Literal['font'] = 'font'
FOREGROUND: Literal['foreground'] = 'foreground'
HIGHLIGHTBACKGROUND: Literal['highlightbackground'] = 'highlightbackground'
INSERTBORDERWIDTH: Literal['insertborderwidth'] = 'insertborderwidth'
INSERTOFFTIME: Literal['insertofftime'] = 'insertofftime'
INSERTONTIME: Literal['insertontime'] = 'insertontime'
INSERTWIDTH: Literal['insertwidth'] = 'insertwidth'
SELECTBORDERWIDTH: Literal['selectborderwidth'] = 'selectborderwidth'
SELECTFOREGROUND: Literal['selectforeground'] = 'selectforeground'
SHOW: Literal['show'] = 'show'
STATE: Literal['state'] = 'state'
TAKEFOCUS: Literal['takefocus'] = 'takefocus'
TEXTVARIABLE: Literal['textvariable'] = 'textvariable'
VALIDATE: Literal['validate'] = 'validate'
VALIDATECOMMAND: Literal['validatecommand'] = 'validatecommand'
VCMD: Literal['vcmd'] = 'vcmd'
WIDTH: Literal['width'] = 'width'
XSCROLLCOMMAND: Literal['xscrollcommand'] = 'xscrollcommand'

# Pack and grid arguments
AFTER: Literal['after'] = 'after'
ANCHOR: Literal['anchor'] = 'anchor'
BEFORE: Literal['before'] = 'before'
EXPAND: Literal['expand'] = 'expand'
FILL: Literal['fill'] = 'fill'
IN_: Literal['in_'] = 'in_'
IPADX: Literal['ipadx'] = 'ipadx'
IPADY: Literal['ipady'] = 'ipady'
PADX: Literal['padx'] = 'padx'
PADY: Literal['pady'] = 'pady'
SIDE: Literal['side'] = 'side'
COLUMN: Literal['column'] = 'column'
COLUMNSPAN: Literal['columnspan'] = 'columnspan'
ROW: Literal['row'] = 'row'
ROWSPAN: Literal['rowspan'] = 'rowspan'
STICKY: Literal['sticky'] = 'sticky'

# Checkbutton arguments
VARIABLE: Literal['variable'] = 'variable'
ONVALUE: Literal['onvalue'] = 'onvalue'
OFFVALUE: Literal['offvalue'] = 'offvalue'

# Combobox arguments
VALUES: Literal['values'] = 'values'

# Listbox arguments
ACTIVE_STYLE: Literal['activestyle'] = 'activestyle'
LISTVARIABLE: Literal['listvariable'] = 'listvariable'

# State values
READONLY: Literal['readonly'] = 'readonly'

# Progressvar arguments
ORIENT: Literal['orient'] = 'orient'
MODE: Literal['mode'] = 'mode'
DETERMINATE: Literal['determinate'] = 'determinate'
INDETERMINATE: Literal['indeterminate'] = 'in' + DETERMINATE
TEXT: Literal['text'] = 'text'
JUSTIFY: Literal['justify'] = 'justify'

# Grid config arguments
WEIGHT: Literal['weight'] = 'weight'


ACCELERATOR: Literal['accelerator'] = 'accelerator'
ACTIVEBACKGROUND: Literal['activebackground'] = 'activebackground'
ACTIVEBORDERWIDTH: Literal['activeborderwidth'] = 'activeborderwidth'
ACTIVEFOREGROUND: Literal['activeforeground'] = 'activeforeground'
ACTIVERELIEF: Literal['activerelief'] = 'activerelief'
ACTIVESTYLE: Literal['activestyle'] = 'activestyle'
ASPECT: Literal['aspect'] = 'aspect'
AUTOSEPARATORS: Literal['autoseparators'] = 'autoseparators'
BACKGROUND: Literal['background'] = 'background'
BD: Literal['bd'] = 'bd'
BELOW: Literal['below'] = 'below'
BG: Literal['bg'] = 'bg'
BITMAP: Literal['bitmap'] = 'bitmap'
BORDERWIDTH: Literal['borderwidth'] = 'borderwidth'
BUTTONBACKGROUND: Literal['buttonbackground'] = 'buttonbackground'
BUTTONCURSOR: Literal['buttoncursor'] = 'buttoncursor'
BUTTONDOWNRELIEF: Literal['buttondownrelief'] = 'buttondownrelief'
BUTTONUP: Literal['buttonup'] = 'buttonup'
CLASS_: Literal['class_'] = 'class_'
CLOSEENOUGH: Literal['closeenough'] = 'closeenough'
COLUMNBREAK: Literal['columnbreak'] = 'columnbreak'
COLUMNS: Literal['columns'] = 'columns'
COMMAND: Literal['command'] = 'command'
COMPOUND: Literal['compound'] = 'compound'
CONFINE: Literal['confine'] = 'confine'
CURSOR: Literal['cursor'] = 'cursor'
DEFAULT: Literal['default'] = 'default'
DIGITS: Literal['digits'] = 'digits'
DIRECTION: Literal['direction'] = 'direction'
DISABLEDBACKGROUND: Literal['disabledbackground'] = 'disabledbackground'
DISABLEDFOREGROUND: Literal['disabledforeground'] = 'disabledforeground'
DISPLAYCOLUMNS: Literal['displaycolumns'] = 'displaycolumns'
ELEMENTBORDERWIDTH: Literal['elementborderwidth'] = 'elementborderwidth'
FLUSH: Literal['flush'] = 'flush'
FORMAT: Literal['format'] = 'format'
FROM_: Literal['from_'] = 'from_'
HANDLEPAD: Literal['handlepad'] = 'handlepad'
HANDLESIZE: Literal['handlesize'] = 'handlesize'
HEIGHT: Literal['height'] = 'height'
HIDEMARGIN: Literal['hidemargin'] = 'hidemargin'
HIGHLIGHTCOLOR: Literal['highlightcolor'] = 'highlightcolor'
HIGHLIGHTTHICKNESS: Literal['highlightthickness'] = 'highlightthickness'
ID: Literal['id'] = 'id'
IID: Literal['iid'] = 'iid'
IMAGE: Literal['image'] = 'image'
INCREMENT: Literal['increment'] = 'increment'
INDEX: Literal['index'] = 'index'
INDICATORON: Literal['indicatoron'] = 'indicatoron'
INSERTBACKGROUND: Literal['insertbackground'] = 'insertbackground'
INVALIDCOMMAND: Literal['invalidcommand'] = 'invalidcommand'
JUMP: Literal['jump'] = 'jump'
LABEL: Literal['label'] = 'label'
LABELANCHOR: Literal['labelanchor'] = 'labelanchor'
LABELWIDGET: Literal['labelwidget'] = 'labelwidget'
LEFT: Literal['left'] = 'left'
LENGTH: Literal['length'] = 'length'
MAXIMUM: Literal['maximum'] = 'maximum'
MAXUNDO: Literal['maxundo'] = 'maxundo'
MENU: Literal['menu'] = 'menu'
MINSIZE: Literal['minsize'] = 'minsize'
MINWIDTH: Literal['minwidth'] = 'minwidth'
OFFRELIEF: Literal['offrelief'] = 'offrelief'
OPAQUERESIZE: Literal['opaqueresize'] = 'opaqueresize'
OPEN: Literal['open'] = 'open'
OVERRELIEF: Literal['overrelief'] = 'overrelief'
PADDING: Literal['padding'] = 'padding'
PARENT: Literal['parent'] = 'parent'
POSTCOMMAND: Literal['postcommand'] = 'postcommand'
READONLYBACKGROUND: Literal['readonlybackground'] = 'readonlybackground'
RELIEF: Literal['relief'] = 'relief'
REPEATDELAY: Literal['repeatdelay'] = 'repeatdelay'
REPEATINTERVAL: Literal['repeatinterval'] = 'repeatinterval'
RESOLUTION: Literal['resolution'] = 'resolution'
RIGHT: Literal['right'] = 'right'
SASHPAD: Literal['sashpad'] = 'sashpad'
SASHRELIEF: Literal['sashrelief'] = 'sashrelief'
SASHWIDTH: Literal['sashwidth'] = 'sashwidth'
SCROLLREGION: Literal['scrollregion'] = 'scrollregion'
SELECTBACKGROUND: Literal['selectbackground'] = 'selectbackground'
SELECTCOLOR: Literal['selectcolor'] = 'selectcolor'
SELECTIMAGE: Literal['selectimage'] = 'selectimage'
SELECTMODE: Literal['selectmode'] = 'selectmode'
SHOWHANDLE: Literal['showhandle'] = 'showhandle'
SHOWVALUE: Literal['showvalue'] = 'showvalue'
SLIDERLENGTH: Literal['sliderlength'] = 'sliderlength'
SLIDERRELIEF: Literal['sliderrelief'] = 'sliderrelief'
SPACING1: Literal['spacing1'] = 'spacing1'
SPACING2: Literal['spacing2'] = 'spacing2'
SPACING3: Literal['spacing3'] = 'spacing3'
STRETCH: Literal['stretch'] = 'stretch'
STYLE: Literal['style'] = 'style'
TABS: Literal['tabs'] = 'tabs'
TAGS: Literal['tags'] = 'tags'
TEAROFF: Literal['tearoff'] = 'tearoff'
TEAROFFCOMMAND: Literal['tearoffcommand'] = 'tearoffcommand'
TICKINTERVAL: Literal['tickinterval'] = 'tickinterval'
TITLE: Literal['title'] = 'title'
TO: Literal['to'] = 'to'
TROUGHCOLOR: Literal['troughcolor'] = 'troughcolor'
UNDERLINE: Literal['underline'] = 'underline'
UNDO: Literal['undo'] = 'undo'
VALUE: Literal['value'] = 'value'
WRAP: Literal['wrap'] = 'wrap'
WRAPLENGTH: Literal['wraplength'] = 'wraplength'
XSCROLLINCREMENT: Literal['xscrollincrement'] = 'xscrollincrement'
YSCROLLCOMMAND: Literal['yscrollcommand'] = 'yscrollcommand'
YSCROLLINCREMENT: Literal['yscrollincrement'] = 'yscrollincrement'
