
import re
import tkinter

#Entry arguments
EXPORTSELECTION = 'exportselection'
FG = 'fg'
FONT = 'font'
FOREGROUND = 'foreground'
HIGHLIGHTBACKGROUND = 'highlightbackground'
INSERTBORDERWIDTH = 'insertborderwidth'
INSERTOFFTIME = 'insertofftime'
INSERTONTIME = 'insertontime'
INSERTWIDTH = 'insertwidth'
SELECTBORDERWIDTH = 'selectborderwidth'
SELECTFOREGROUND = 'selectforeground'
SHOW = 'show'
STATE = 'state'
TAKEFOCUS = 'takefocus'
TEXTVARIABLE = 'textvariable'
VALIDATE = 'validate'
VALIDATECOMMAND = 'validatecommand'
VCMD = 'vcmd'
WIDTH = 'width'
XSCROLLCOMMAND = 'xscrollcommand'

#Pack and grid arguments
AFTER = 'after'
ANCHOR = 'anchor'
BEFORE = 'before'
EXPAND = 'expand'
FILL = 'fill'
IN_ = 'in_'
IPADX = 'ipadx'
IPADY = 'ipady'
PADX = 'padx'
PADY = 'pady'
SIDE = 'side'
COLUMN = 'column'
COLUMNSPAN = 'columnspan'
ROW = 'row'
ROWSPAN = 'rowspan'
STICKY = 'sticky'

#Checkbutton arguments
VARIABLE = 'variable'
ONVALUE = 'onvalue'
OFFVALUE = 'offvalue'

#Combobox arguments
VALUES = 'values'

#Listbox arguments
ACTIVE_STYLE = 'activestyle'
LISTVARIABLE = 'listvariable'

#State values
READONLY = 'readonly'

#Progressvar arguments
ORIENT = 'orient'
MODE = 'mode'
DETERMINATE = 'determinate'
INDETERMINATE = 'in' + DETERMINATE
TEXT = 'text'
JUSTIFY = 'justify'

#Grid config arguments
WEIGHT = 'weight'


ACCELERATOR = 'accelerator'
ACTIVEBACKGROUND = 'activebackground'
ACTIVEBORDERWIDTH = 'activeborderwidth'
ACTIVEFOREGROUND = 'activeforeground'
ACTIVERELIEF = 'activerelief'
ACTIVESTYLE = 'activestyle'
ASPECT = 'aspect'
AUTOSEPARATORS = 'autoseparators'
BACKGROUND = 'background'
BD = 'bd'
BELOW = 'below'
BG = 'bg'
BITMAP = 'bitmap'
BORDERWIDTH = 'borderwidth'
BUTTONBACKGROUND = 'buttonbackground'
BUTTONCURSOR = 'buttoncursor'
BUTTONDOWNRELIEF = 'buttondownrelief'
BUTTONUP = 'buttonup'
CLASS_ = 'class_'
CLOSEENOUGH = 'closeenough'
COLUMNBREAK = 'columnbreak'
COLUMNS = 'columns'
COMMAND = 'command'
COMPOUND = 'compound'
CONFINE = 'confine'
CURSOR = 'cursor'
DEFAULT = 'default'
DIGITS = 'digits'
DIRECTION = 'direction'
DISABLEDBACKGROUND = 'disabledbackground'
DISABLEDFOREGROUND = 'disabledforeground'
DISPLAYCOLUMNS = 'displaycolumns'
ELEMENTBORDERWIDTH = 'elementborderwidth'
FLUSH = 'flush'
FORMAT = 'format'
FROM_ = 'from_'
HANDLEPAD = 'handlepad'
HANDLESIZE = 'handlesize'
HEIGHT = 'height'
HIDEMARGIN = 'hidemargin'
HIGHLIGHTCOLOR = 'highlightcolor'
HIGHLIGHTTHICKNESS = 'highlightthickness'
ID = 'id'
IID = 'iid'
IMAGE = 'image'
INCREMENT = 'increment'
INDEX = 'index'
INDICATORON = 'indicatoron'
INSERTBACKGROUND = 'insertbackground'
INVALIDCOMMAND = 'invalidcommand'
JUMP = 'jump'
LABEL = 'label'
LABELANCHOR = 'labelanchor'
LABELWIDGET = 'labelwidget'
LEFT = 'left'
LENGTH = 'length'
MAXIMUM = 'maximum'
MAXUNDO = 'maxundo'
MENU = 'menu'
MINSIZE = 'minsize'
MINWIDTH = 'minwidth'
OFFRELIEF = 'offrelief'
OPAQUERESIZE = 'opaqueresize'
OPEN = 'open'
OVERRELIEF = 'overrelief'
PADDING = 'padding'
PARENT = 'parent'
POSTCOMMAND = 'postcommand'
READONLYBACKGROUND = 'readonlybackground'
RELIEF = 'relief'
REPEATDELAY = 'repeatdelay'
REPEATINTERVAL = 'repeatinterval'
RESOLUTION = 'resolution'
RIGHT = 'right'
SASHPAD = 'sashpad'
SASHRELIEF = 'sashrelief'
SASHWIDTH = 'sashwidth'
SCROLLREGION = 'scrollregion'
SELECTBACKGROUND = 'selectbackground'
SELECTCOLOR = 'selectcolor'
SELECTIMAGE = 'selectimage'
SELECTMODE = 'selectmode'
SHOWHANDLE = 'showhandle'
SHOWVALUE = 'showvalue'
SLIDERLENGTH = 'sliderlength'
SLIDERRELIEF = 'sliderrelief'
SPACING1 = 'spacing1'
SPACING2 = 'spacing2'
SPACING3 = 'spacing3'
STRETCH = 'stretch'
STYLE = 'style'
TABS = 'tabs'
TAGS = 'tags'
TEAROFF = 'tearoff'
TEAROFFCOMMAND = 'tearoffcommand'
TICKINTERVAL = 'tickinterval'
TITLE = 'title'
TO = 'to'
TROUGHCOLOR = 'troughcolor'
UNDERLINE = 'underline'
UNDO = 'undo'
VALUE = 'value'
WRAP = 'wrap'
WRAPLENGTH = 'wraplength'
XSCROLLINCREMENT = 'xscrollincrement'
YSCROLLCOMMAND = 'yscrollcommand'
YSCROLLINCREMENT = 'yscrollincrement'
